const letters=document.querySelectorAll('.letter');letters.forEach((letter,index)=>{letter.style.animationDelay=`${index * 0.1}s`;letter.style.opacity=1});var userLanguage="ar";document.addEventListener("DOMContentLoaded",function(){const eng=document.getElementById('en');const ar=document.getElementById('ar');eng.addEventListener('click',function(){userLanguage="en";console.log("User language set to English")});ar.addEventListener('click',function(){console.log("User language set to Arabic");userLanguage="ar"})});const projectImg=document.querySelector('.projectImg');const imagesContainer=document.querySelector('.projectImg');let images=document.querySelectorAll('.inlineBlock');function centerImage(index){const imageToCenter=images[index];const imageWidth=imageToCenter.clientWidth;const containerWidth=projectImg.clientWidth;const imageOffset=imageToCenter.offsetLeft;const scrollPosition=imageOffset-(containerWidth/2)+(imageWidth/2);projectImg.scrollTo({left:scrollPosition,behavior:'smooth'})}
window.addEventListener('load',()=>{centerImage(2)});function getClosestImageToCenter(){const containerWidth=projectImg.clientWidth;const center=projectImg.scrollLeft+(containerWidth/2);let closestIndex=0;let minDistance=Infinity;images.forEach((image,index)=>{const imageCenter=image.offsetLeft+(image.clientWidth/2);const distance=Math.abs(center-imageCenter);if(distance<minDistance){minDistance=distance;closestIndex=index}});return closestIndex}
let autoScroll=function(){setTimeout(()=>{projectImg.scrollLeft+=500},200)}
let setsedIndex=document.querySelector('.img1');let setsedIndex2=document.querySelector('.img1');function activeImg(index){let currentIndexImg=index+1;const activeI=images[index];activeI.classList.add('activeImgDiv');const activeI2=document.querySelector('.img'+parseInt(activeI.id));activeI2.classList.add('activeImg');setsedIndex=activeI;setsedIndex2=activeI2}
let isScrolling;projectImg.addEventListener('scroll',()=>{clearTimeout(isScrolling);if(setsedIndex.classList.contains('activeImgDiv')&&setsedIndex2.classList.contains('activeImg')){setsedIndex.classList.remove('activeImgDiv');setsedIndex2.classList.remove('activeImg')}
isScrolling=setTimeout(()=>{const closestImageIndex=getClosestImageToCenter();centerImage(closestImageIndex);activeImg(closestImageIndex)},200);const scrollLeft=projectImg.scrollLeft;const maxScrollLeft=projectImg.scrollWidth-projectImg.clientWidth;if(scrollLeft>=maxScrollLeft-1){const firstImage=images[0];imagesContainer.appendChild(firstImage);projectImg.scrollLeft-=firstImage.clientWidth}
if(scrollLeft<=0){const lastImage=images[images.length-1];imagesContainer.prepend(lastImage);projectImg.scrollLeft+=lastImage.clientWidth}
images=document.querySelectorAll('.inlineBlock')});window.addEventListener('scroll',function(){const header=document.querySelector('.header');if(window.scrollY>50){header.classList.add('scrolled')}else{header.classList.remove('scrolled')}});document.addEventListener("DOMContentLoaded",()=>{const icons=document.querySelectorAll(".UVPrinterIconImG, .CNCIconImg, .JOINERVIconImg , .paintIconIMG ,.DesignerIconIMG ,.BlacksmithIconIMG ,.steckerIconIMG");const observer=new IntersectionObserver((entries,observer)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("in-view")}else{entry.target.classList.remove("in-view")}})},{threshold:0.5});icons.forEach(icon=>observer.observe(icon))});var closeBtn=document.getElementById('closeBtn');closeBtn.addEventListener('click',function(){var popup=document.getElementById('departmentInfo');popup.style.display='none'});var UVPrinterIconImG=document.querySelector('.UVPrinterIconImG');var CNCIconImg=document.querySelector('.CNCIconImg');var JOINERVIconImg=document.querySelector('.JOINERVIconImg');var paintIconIMG=document.querySelector('.paintIconIMG');var DesignerIconIMG=document.querySelector('.DesignerIconIMG');var BlacksmithIconIMG=document.querySelector('.BlacksmithIconIMG');var steckerIcon=document.querySelector('.steckerIcon');let printTxt="يتميز قسم الطباعة بتقنيات طباعة متقدمة، مما يتيح لنا تقديم خدمات متنوعة، مثل الطباعة بالأشعة فوق البنفسجية للحصول على ألوان نابضة بالحياة تدوم طويلاً، إلى جانب طباعة الملصقات المخصصة للعلامات التجارية. نحن نحول أفكارك إلى واقع على مجموعة واسعة من المواد بجودة عالية وأثر بصري قوي."
let CNCTxt="يتخصص قسم سي إن سي لدينا في قطع المواد بدقة، مثل الخشب والرغوة والبلاستيك. يضمن مشغلونا المهرة وآلاتنا عالية الجودة تصاميم دقيقة ومتقنة، مما يمكننا من إنشاء قطع مخصصة تضيف قيمة إلى أي عرض أو إعداد ترويجي."
let JOINERVTxt="يركز قسم النجارة على تصنيع الأعمال الخشبية المخصصة عالية الجودة. من الأكشاك إلى الهياكل المخصصة للعرض، يقوم فريقنا بإنتاج قطع متينة وأنيقة تندمج ضمن تجهيزات العرض والإعلانات. يضمن اهتمامهم بالتفاصيل تقديم مشاريع تتميز بالثبات والجمال."
let paintTxt="يقدم قسم الدهانات اللمسات النهائية التي تضفي الحياة على مشاريعنا. باستخدام مجموعة من الألوان والتشطيبات، يقوم فريقنا من الرسامين بإضافة الحيوية والحماية، مما يزيد من جاذبية وجمال وديمومة كل قطعة ننتجها."
let DesignerTxt="يتميز قسم التصميم لدينا بالإبداع والابتكار الذي يضفي لمسات فريدة على كل مشروع نقوم به. يعمل فريق التصميم باحترافية عالية لإنتاج تصاميم بصرية جذابة ومتميزة تشكل جوهر تجهيزات العرض وتضيف لمسات جمالية تتناسب مع رغبات وأهداف العملاء. نسعى دائماً لتحقيق التوازن بين الشكل والوظيفة، بحيث تكون كل قطعة ملفتة للنظر وفعّالة في الوقت ذاته، مما يضمن تحقيق رؤية العميل بشكل كامل واحترافي."
let BlacksmithTxt="يجمع قسم الحدادة بين المهارات التقليدية والتقنيات الحديثة لتقديم أعمال معدنية متينة ومخصصة. سواء كانت إطارات قوية للعرض أو عناصر زخرفية فريدة أو قواعد ثابتة، يضمن فريقنا من الحدادين الدقة والصلابة في كل مشروع."
let steckerTxt="يهتم قسم الملصقات لدينا بإنتاج ملصقات عالية الجودة تلبي احتياجات عملائنا بدقة. بدءًا من الملصقات المميزة إلى الملصقات المخصصة للعلامات التجارية، نتولى عملية الإنتاج بالكامل، بما في ذلك دمج الإضاءة ووضع اللمسات النهائية بعناية. صُممت ملصقاتنا لتدوم وتناسب الاستخدام الداخلي والخارجي."
let printTitle="قسم الطباعة";let CNCTitle="قسم CNC";let JOINERTitle="قسم النجارة";let paintTitle="قسم الدهانات";let DesignerTitle="قسم التصميم";let BlacksmithTitle="قسم الحدادة";let steckerTitle="قسم الملصقات";function updateLang(){if(userLanguage=='ar'){printTxt="يتميز قسم الطباعة بتقنيات طباعة متقدمة، مما يتيح لنا تقديم خدمات متنوعة، مثل الطباعة بالأشعة فوق البنفسجية للحصول على ألوان نابضة بالحياة تدوم طويلاً، إلى جانب طباعة الملصقات المخصصة للعلامات التجارية. نحن نحول أفكارك إلى واقع على مجموعة واسعة من المواد بجودة عالية وأثر بصري قوي."
CNCTxt="يتخصص قسم سي إن سي لدينا في قطع المواد بدقة، مثل الخشب والرغوة والبلاستيك. يضمن مشغلونا المهرة وآلاتنا عالية الجودة تصاميم دقيقة ومتقنة، مما يمكننا من إنشاء قطع مخصصة تضيف قيمة إلى أي عرض أو إعداد ترويجي."
JOINERVTxt="يركز قسم النجارة على تصنيع الأعمال الخشبية المخصصة عالية الجودة. من الأكشاك إلى الهياكل المخصصة للعرض، يقوم فريقنا بإنتاج قطع متينة وأنيقة تندمج ضمن تجهيزات العرض والإعلانات. يضمن اهتمامهم بالتفاصيل تقديم مشاريع تتميز بالثبات والجمال."
paintTxt="يقدم قسم الدهانات اللمسات النهائية التي تضفي الحياة على مشاريعنا. باستخدام مجموعة من الألوان والتشطيبات، يقوم فريقنا من الرسامين بإضافة الحيوية والحماية، مما يزيد من جاذبية وجمال وديمومة كل قطعة ننتجها."
DesignerTxt="يتميز قسم التصميم لدينا بالإبداع والابتكار الذي يضفي لمسات فريدة على كل مشروع نقوم به. يعمل فريق التصميم باحترافية عالية لإنتاج تصاميم بصرية جذابة ومتميزة تشكل جوهر تجهيزات العرض وتضيف لمسات جمالية تتناسب مع رغبات وأهداف العملاء. نسعى دائماً لتحقيق التوازن بين الشكل والوظيفة، بحيث تكون كل قطعة ملفتة للنظر وفعّالة في الوقت ذاته، مما يضمن تحقيق رؤية العميل بشكل كامل واحترافي."
BlacksmithTxt="يجمع قسم الحدادة بين المهارات التقليدية والتقنيات الحديثة لتقديم أعمال معدنية متينة ومخصصة. سواء كانت إطارات قوية للعرض أو عناصر زخرفية فريدة أو قواعد ثابتة، يضمن فريقنا من الحدادين الدقة والصلابة في كل مشروع."
steckerTxt="يهتم قسم الملصقات لدينا بإنتاج ملصقات عالية الجودة تلبي احتياجات عملائنا بدقة. بدءًا من الملصقات المميزة إلى الملصقات المخصصة للعلامات التجارية، نتولى عملية الإنتاج بالكامل، بما في ذلك دمج الإضاءة ووضع اللمسات النهائية بعناية. صُممت ملصقاتنا لتدوم وتناسب الاستخدام الداخلي والخارجي."
printTitle="قسم الطباعة";CNCTitle="قسم CNC";JOINERTitle="قسم النجارة";paintTitle="قسم الدهانات";DesignerTitle="قسم التصميم";BlacksmithTitle="قسم الحدادة";steckerTitle="قسم الملصقات"}else{printTxt="Equipped with advanced printing technology, our Printing Department provides versatile services, from UV printing for vibrant, long-lasting colors to custom sticker printing for branding. We bring your ideas to life on a wide range of materials, offering high-quality, impactful prints for any purpose."
CNCTxt="In the CNC Department, we specialize in precision cutting for materials like wood, foam, and plastics. Our expert operators and top-tier machinery ensure accurate and intricate designs, enabling us to create custom pieces that enhance any display or promotional setup. "
JOINERVTxt="Our Joinery Department focuses on crafting custom, high-quality woodwork. From booths and stands to unique display setups, our joiners create sturdy, stylish pieces that are integral to our advertising installations. Their expertise ensures each project is finished with an eye for detail and durability."
paintTxt="The Paint Department provides finishing touches that bring our projects to life. Using a range of colors and finishes, our skilled painters add vibrancy and protection, enhancing both the visual appeal and longevity of every piece we produce."
DesignerTxt="Our Design Department brings creativity and innovation to every project. Skilled in 3D Max, Photoshop, and Illustrator, our designers create stunning visuals that form the foundation of our physical displays, ensuring that each project is eye-catching, functional, and aligned with our clients' vision."
BlacksmithTxt="The Blacksmith Department combines traditional skills with modern techniques to deliver durable, custom-made metalwork. Whether it’s sturdy frames for displays, unique decorative elements, or robust stands, our blacksmith team ensures precision and resilience in every project."
steckerTxt="Our Sticker Department is dedicated to crafting high-quality stickers that meet the specific needs of our clients. From eye-catching decals to branding essentials, we handle the full process, including LED integration and meticulous collection and finishing touches. Our stickers are designed to last, with options that suit indoor and outdoor applications."
printTitle="Printing Department"
CNCTitle="CNC Department"
JOINERTitle="Joinery Department"
paintTitle="Paint Department"
DesignerTitle="Designer Department"
BlacksmithTitle="Blacksmith Department"
steckerTitle="Sticker Department"}}
UVPrinterIconImG.addEventListener('click',function(){var popup=document.getElementById('departmentInfo');var departmentInfo__title=document.querySelector('.departmentInfo__title');var body=document.querySelector('.body');updateLang();departmentInfo__title.textContent=printTitle;body.innerHTML=`
    <img src="SC-V7000_01-headon_690x460.jpg" alt="" class="printIMG col-12">
    <p class="printingTXT">
    ${printTxt}
    </p>`;popup.style.display='flex'});CNCIconImg.addEventListener('click',function(){var popup=document.getElementById('departmentInfo');var departmentInfo__title=document.querySelector('.departmentInfo__title');var body=document.querySelector('.body');updateLang();departmentInfo__title.textContent=CNCTitle;body.innerHTML=`
    <img src="1-15112R330080-L.jpg" alt="" class="printIMG col-12">
    <p class="printingTXT">
      ${CNCTxt}
    </p>`;popup.style.display='flex'});JOINERVIconImg.addEventListener('click',function(){var popup=document.getElementById('departmentInfo');var departmentInfo__title=document.querySelector('.departmentInfo__title');var body=document.querySelector('.body');updateLang();departmentInfo__title.textContent=JOINERTitle;body.innerHTML=`
    <img src="Joinery-Services-scaled.jpeg" alt="" class="printIMG col-12">
    <p class="printingTXT">
      ${JOINERVTxt}
    </p>`;popup.style.display='flex'});paintIconIMG.addEventListener('click',function(){var popup=document.getElementById('departmentInfo');var departmentInfo__title=document.querySelector('.departmentInfo__title');var body=document.querySelector('.body');updateLang();departmentInfo__title.textContent=paintTitle;body.innerHTML=`
    <img src="images.jpeg" alt="" class="printIMG col-12">
    <p class="printingTXT">
      ${paintTxt}
    </p>`;popup.style.display='flex'});DesignerIconIMG.addEventListener('click',function(){var popup=document.getElementById('departmentInfo');var departmentInfo__title=document.querySelector('.departmentInfo__title');var body=document.querySelector('.body');updateLang();departmentInfo__title.textContent=DesignerTitle;body.innerHTML=`
    <img src="2b29159cb43b168de59db340db81027f5f6cdd2b-migrating-from-3ds-max-to-cinema-4d-in-professional-arch-viz-part-1-1.jpg" alt="" class="printIMG col-12">
    <p class="printingTXT">
      ${DesignerTxt}
    </p>`;popup.style.display='flex'});BlacksmithIconIMG.addEventListener('click',function(){var popup=document.getElementById('departmentInfo');var departmentInfo__title=document.querySelector('.departmentInfo__title');var body=document.querySelector('.body');updateLang();departmentInfo__title.textContent=BlacksmithTitle;body.innerHTML=`
    <img src="Martin-Bustamante-12868647634_980d853d34_o-e1612362182502.jpg" alt="" class="printIMG col-12">
    <p class="printingTXT">
      ${BlacksmithTxt}
    </p>`;popup.style.display='flex'});steckerIcon.addEventListener('click',function(){var popup=document.getElementById('departmentInfo');var departmentInfo__title=document.querySelector('.departmentInfo__title');var body=document.querySelector('.body');updateLang();departmentInfo__title.textContent=steckerTitle;body.innerHTML=`
    <img src="graphtec-fcx4000-60-es-flatbed-cutter-384-x-259-graphtec-bundle-graphtec-923947_2048x.jpg" alt="" class="printIMG col-12">
    <p class="printingTXT">
      ${steckerTxt}
    </p>`;popup.style.display='flex'});var chatHistory="";let messagecounter=0;const chatBack=document.getElementById('chatBack');const robotImg=document.querySelector('.robotImg');robotImg.addEventListener('click',function(){chatBack.style.display='flex'});const string1="sk-proj"
const chatTxt=document.getElementById('chatTxt');chatTxt.addEventListener('keydown',function(event){if(event.key==='Enter'){sendMesg(chatTxt.value);chatTxt.value=''}});async function sendMesg(chatMesg){const text=string1+"-Y6S2oi84nj-gGlaWWApSWmAtMEBmx2Qj_DMU8T9Ri-GXiO_";const apiUrl="https://api.openai.com/v1/chat/completions";chatHistory+=("message hestory "+messagecounter+" {role: 'user', content: "+chatMesg+"}");messagecounter++;const data={model:"gpt-4",messages:[{role:"system",content:"what dose the user asking about choose between the following options: 1. a normal qustion 2. image generation    >>Note:the response must be in this format: 1 or 2"},{role:"user",content:chatHistory}]};generateChatContainerUser(chatMesg);TypingMessage();console.log(othertext(text)+"F35oBGATYVyGrdCQP-Idh8A")
try{const response=await fetch(apiUrl,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${othertext(text)+"F35oBGATYVyGrdCQP-Idh8A"}`},body:JSON.stringify(data)});if(response.ok){const result=await response.json();const aiResponse=result.choices[0].message.content;if(aiResponse.includes("2")){const imageUrl=await generateImage(chatMesg);return}else{sendCompletionMesage(chatMesg)}}else{console.error("API request failed:",response.status,response.statusText)}}catch(error){console.error("An error occurred:",error)}}
async function generateImage(imageTxt){const text=string1+"-Y6S2oi84nj-gGlaWWApSWmAtMEBmx2Qj_DMU8T9Ri-GXiO_";const apiUrl="https://api.openai.com/v1/images/generations";const data={model:"dall-e-3",prompt:chatHistory,n:1,size:"1024x1024"};try{const response=await fetch(apiUrl,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${othertext(text)+"F35oBGATYVyGrdCQP-Idh8A"}`},body:JSON.stringify(data)});if(response.ok){const result=await response.json();const imageUrl=result.data[0].url;displayImage(imageUrl);chatHistory+=("message hestory "+messagecounter+" {role: 'assistant', content: "+imageUrl+"}")}else{console.error("API request failed:",response.status,response.statusText)}}catch(error){console.error("An error occurred:",error)}}
function displayImage(imageUrl){const chatTxt=document.getElementById('chatTxt');chatTxt.disabled=!1;const TypingMessage=document.querySelector('.TypingMessage');TypingMessage.remove();const chatContainer=document.createElement('div');chatContainer.classList.add('chatContainerTxt');const chatBody=document.querySelector('.chatBody');const img=document.createElement('img');img.src=imageUrl;img.alt="Generated image";img.style.width="100%";img.classList.add('generatedImageStyle');chatContainer.appendChild(img);chatBody.appendChild(chatContainer);const element=document.querySelector(".chatBody");element.scrollTo({top:element.scrollHeight,behavior:"smooth"})}
function generateChatContainerUser(chatTxt){const chatContainer=document.createElement('div');chatContainer.classList.add('chatContainerUser');const chatBody=document.querySelector('.chatBody');const messageElement=document.createElement('p');messageElement.className="userMessage";messageElement.textContent=chatTxt;chatContainer.appendChild(messageElement);chatBody.appendChild(chatContainer);const element=document.querySelector(".chatBody");element.scrollTo({top:element.scrollHeight,behavior:"smooth"})}
async function sendCompletionMesage(chatMesg){const text=string1+"-Y6S2oi84nj-gGlaWWApSWmAtMEBmx2Qj_DMU8T9Ri-GXiO_";const apiUrl="https://api.openai.com/v1/chat/completions";const data={model:"gpt-4",messages:[{role:"system",content:"If the user asks about our company: We are an advertising company that prints stickers, flex, UV prints, creates stands, and other advertising and printing products, including LED logos."},{role:"user",content:chatHistory}]};try{const response=await fetch(apiUrl,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${othertext(text)+"F35oBGATYVyGrdCQP-Idh8A"}`},body:JSON.stringify(data)});if(response.ok){const result=await response.json();const aiResponse=result.choices[0].message.content;displayMessage(aiResponse);chatHistory+=("message hestory "+messagecounter+" {role: 'assistant', content: "+aiResponse+"}")}else{console.error("API request failed:",response.status,response.statusText)}}catch(error){console.error("An error occurred:",error)}}
document.addEventListener("click",function(event){const chatBackground=document.getElementById("chatBack");const chatContainer=document.querySelector(".chatContainer");if(!chatContainer.contains(event.target)&&chatBackground.contains(event.target)){chatBackground.style.display="none"}});function displayMessage(message){const chatTxt=document.getElementById('chatTxt');chatTxt.disabled=!1;const TypingMessage=document.querySelector('.TypingMessage');TypingMessage.remove();const chatContainer=document.createElement('div');const chatBody=document.querySelector('.chatBody');const messageElement=document.createElement('p');messageElement.className="aiMessage";messageElement.textContent=message;chatContainer.appendChild(messageElement);chatBody.appendChild(chatContainer);const element=document.querySelector(".chatBody");element.scrollTo({top:element.scrollHeight,behavior:"smooth"})}
function TypingMessage(){const chatTxt=document.getElementById('chatTxt');chatTxt.disabled=!0;const chatContainer=document.createElement('div');chatContainer.classList.add('TypingMessage');chatContainer.classList.add('aiMessage');const chatBody=document.querySelector('.chatBody');const img=document.createElement('img');img.src="loading-discord-grey.gif";img.alt="Generated image";img.style.width="50px";img.classList.add('generatedImageStyle');chatContainer.appendChild(img);chatBody.appendChild(chatContainer);const element=document.querySelector(".chatBody");element.scrollTo({top:element.scrollHeight,behavior:"smooth"})}
function othertext(text){text+="Dohw0xHYCwJxFq5oz7rEmbbQf2KT3BlbkFJa6ZdRt7sypZoVHhfIw3Ot9UUiMeTzca8TA1TXNQklP9cKNVw1Yc"
return text}
